### ISSUE TITLE
mpi run process() function hangs at some cases

### ISSUE THREAD

**Issue by wjlei1990** [SeismicData/pyasdf#10] opened 2015-10-30 14:24 UTC
Hi Lion,

I am trying to run a data processing using the process() function in mpi environment.

In the following case, I got 10 asdf file to process and I am using 4 processors. So I go through them one by one and delete the dataset when I am done with it. I got such errors after the program runs for a certain time(for example, after processing 4 files and now it is processing the 5th):
```
====================
Dir info:
input asdf: /lustre/atlas/proj-shared/geo111/Wenjie/DATA_SI/ASDF_new/raw/synt/C200502151442A.Mpp.synthetic.h5
output asdf: /lustre/atlas/proj-shared/geo111/Wenjie/DATA_SI/ASDF_new/proc/synt/C200502151442A.Mpp.proc_synt_50_100.h5
Processing info:
filter band: [40.0, 50.0, 100.0, 150.0]
tag map: {"synthetic" ==> "proc_synt_50_100"}
interp relative start and end(to eventcentroid time): (0.00    ,  6000.00)
interp deltat: 0.5
output_asdf exists and removed:/lustre/atlas/proj-shared/geo111/Wenjie/DATA_SI/ASDF_new/proc/synt/C200502151442A.Mpp.proc_synt_50_100.h5
Launching processing using MPI on 4 processors.
Jobs (running 2.17 seconds): queued: 142 | finished: 0 | total: 161
	Worker 1: 9 active, 0 completed jobs
	Worker 2: 9 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 4.36 seconds): queued: 123 | finished: 0 | total: 161
	Worker 1: 19 active, 0 completed jobs
	Worker 2: 18 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 6.51 seconds): queued: 105 | finished: 0 | total: 161
	Worker 1: 27 active, 0 completed jobs
	Worker 2: 28 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 8.67 seconds): queued: 90 | finished: 0 | total: 161
	Worker 1: 35 active, 0 completed jobs
	Worker 2: 35 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 10.81 seconds): queued: 76 | finished: 0 | total: 161
	Worker 1: 42 active, 0 completed jobs
	Worker 2: 42 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 12.87 seconds): queued: 62 | finished: 0 | total: 161
	Worker 1: 49 active, 0 completed jobs
	Worker 2: 49 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 15.02 seconds): queued: 45 | finished: 0 | total: 161
	Worker 1: 57 active, 0 completed jobs
	Worker 2: 58 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 17.09 seconds): queued: 29 | finished: 0 | total: 161
	Worker 1: 66 active, 0 completed jobs
	Worker 2: 65 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 19.13 seconds): queued: 13 | finished: 0 | total: 161
	Worker 1: 74 active, 0 completed jobs
	Worker 2: 73 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs

Jobs (running 21.90 seconds): queued: 0 | finished: 0 | total: 161
	Worker 1: 80 active, 0 completed jobs
	Worker 2: 80 active, 0 completed jobs
	Worker 3: 1 active, 0 completed jobs
```
It seems the "Worker 3" is not reponding. So the program just hangs up. I am not quite sure what trigers that.

It might be some memory issues here since if I am using 16 cores, the problem never shows up. I am not quite sure. I will dive into the code and see if I can find the bug. 

Or maybe it is not good to run several dataset processing in one mpirun(maybe the python is not good at this kind of memory management). So in the future, it will be safer to process one file at one mpiexec call.

**Comment by krischer** [comment] 2015-10-30 14:48
Hey Wenjie,

does it always happen after the 4th file or it is random? I thought I found all the MPI communication edge cases :-( It should definitely work and I'd be quite happy to help debug the issue.

Can you run it with 

```python
ASDFDataSet(..., debug=True)
```

It will produce an enormous amount of output as it prints out the whole MPI communication but it should help find whats wrong. Can you please upload the output to pastebin or somewhere else?

Thanks!

Lion

**Comment by wjlei1990** [comment] 2015-10-30 16:12
I did another 5 test.

First three stops at the 3rd file on Worker 2.

Last two stops at the 6th file on Worker 1.

I will turn on the debug and keep you updated.

**Comment by wjlei1990** [comment] 2015-10-30 17:22
the "debug=True" flag is not working on my machine... I will try to figure it out now.

```
mpiexec -n 2 process_synthetic.py -f proc_synt.dirs.json -p proc_synt.params.json -v
====================
Dir info:
input asdf: /lustre/atlas/proj-shared/geo111/Wenjie/DATA_SI/ASDF_new/raw/synt/C200502151442A.synthetic.h5
output asdf: /lustre/atlas/proj-shared/geo111/Wenjie/DATA_SI/ASDF_new/proc/synt/C200502151442A.proc_synt_50_100.h5
Processing info:
filter band: [40.0, 50.0, 100.0, 150.0]
tag map: {"synthetic" ==> "proc_synt_50_100"}
interp relative start and end(to eventcentroid time): (0.00    ,  6000.00)
interp deltat: 0.5
output_asdf exists and removed:/lustre/atlas/proj-shared/geo111/Wenjie/DATA_SI/ASDF_new/proc/synt/C200502151442A.proc_synt_50_100.h5
/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py:129: ASDFWarning: Compression will be disabled as parallel HDF5 does not support compression
  warnings.warn(msg, ASDFWarning)
/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py:129: ASDFWarning: Compression will be disabled as parallel HDF5 does not support compression
  warnings.warn(msg, ASDFWarning)
Launching processing using MPI on 2 processors.
Traceback (most recent call last):
  File "/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf/process_synthetic.py", line 126, in <module>
Traceback (most recent call last):
  File "/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf/process_synthetic.py", line 126, in <module>
    proc.smart_run()
  File "/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf/process_synthetic.py", line 111, in smart_run
    proc.smart_run()
  File "/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf/process_synthetic.py", line 111, in smart_run
    self.proc_synt_asdf(_par, _file)
  File "/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf/process_synthetic.py", line 95, in proc_synt_asdf
    self.proc_synt_asdf(_par, _file)
  File "/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf/process_synthetic.py", line 95, in proc_synt_asdf
    interp_deltat=par_obj.interp_deltat)
  File "/autofs/nccs-svm1_home1/lei/source_inversion_wf/src/preproc_asdf/proc_util.py", line 204, in process_synt
    interp_deltat=par_obj.interp_deltat)
  File "/autofs/nccs-svm1_home1/lei/source_inversion_wf/src/preproc_asdf/proc_util.py", line 204, in process_synt
    ds.process(process_function, outputfn, tag_map=tag_map)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1417, in process
    ds.process(process_function, outputfn, tag_map=tag_map)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1417, in process
    station_tags, tag_map)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1433, in _dispatch_processing_mpi
    station_tags, tag_map)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1430, in _dispatch_processing_mpi
    output_data_set, tag_map)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1569, in _dispatch_processing_mpi_worker_node
    station_tags, tag_map)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1496, in _dispatch_processing_mpi_master_node
    self._send_mpi(None, 0, "WORKER_REQUESTS_ITEM", blocking=False)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/asdf_data_set.py", line 1775, in _send_mpi
    pretty_receiver_log(source, self.mpi.rank, status.tag, msg)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/utils.py", line 981, in pretty_receiver_log
    _pretty_log(prefix, rank, source, tag, payload)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/utils.py", line 1008, in _pretty_log
    pretty_sender_log(dest, self.mpi.rank, tag, obj)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/utils.py", line 975, in pretty_sender_log
    tag = tag_colors[tags.index(tag) % len(tag_colors)] + tag + \
ValueError: u'WORKER_REQUESTS_ITEM' is not in list
    _pretty_log(prefix, destination, rank, tag, payload)
  File "/autofs/nccs-svm1_home1/lei/software/pyasdf/pyasdf/utils.py", line 1008, in _pretty_log
    tag = tag_colors[tags.index(tag) % len(tag_colors)] + tag + \
ValueError: u'WORKER_REQUESTS_ITEM' is not in list
-------------------------------------------------------
Primary job  terminated normally, but 1 process returned
a non-zero exit code.. Per user-direction, the job has been aborted.
-------------------------------------------------------
--------------------------------------------------------------------------
mpiexec detected that one or more processes exited with non-zero status, thus causing
the job to be terminated. The first process to do so was:

  Process name: [[1621,1],1]
  Exit code:    1
--------------------------------------------------------------------------
```

**Comment by wjlei1990** [comment] 2015-10-30 19:28
Hi Lion,

It seems I have located the bug for the "debug" flag.

```
    # Deterministic colors also on Python 3.                                    
    msg_tag_keys = sorted(MSG_TAGS.keys(), key=lambda x: str(x))                
    tags = [i for i in msg_tag_keys if isinstance(i, (str, bytes))]             
    print("see 1:", msg_tag_keys)                                               
                                                                                
    tag = MSG_TAGS[tag]                                                         
    print("see here:", tag, tags)                                               
                                                                                
    tag = tag_colors[tags.index(tag) % len(tag_colors)] + tag + \               
        colorama.Style.RESET_ALL    
```

**Comment by krischer** [comment] 2015-10-30 19:52
The `debug=True` bug should be fixed in a081348dc6738621ff25eab1308ca7d50afe7a62.

**Comment by wjlei1990** [comment] 2015-11-02 00:28
[run1.log.txt](https://github.com/SeismicData/pyasdf/files/24979/run1.log.txt)

Hi Lion,

Please see line 7423 where it starts to process the last file.

Check Line
```
/ccs/home/lei/source_inversion_wf/src/preproc_asdf/test_wf
```

**Comment by wjlei1990** [comment] 2015-11-02 02:49
![screenshot from 2015-11-01 21 47 43](https://cloud.githubusercontent.com/assets/5777547/10873421/7924fb94-80e2-11e5-9a94-a8a59f520a46.png)

**Comment by wjlei1990** [comment] 2015-11-02 05:15
aHi Lion,

Could you clarify here a little bit? Line 1505 - 1507 in asdf_data_set.py.
```
            if (len(workers_requesting_write) >= 0.5 * self.mpi.comm.size) or \
                    (len(workers_requesting_write) and
                     jobs.all_poison_pills_received):
```
Could you use parenthese to make the logic more clear? I am little confused about the **or** and **and**

**Comment by QuLogic** [comment] 2015-11-09 02:04
There are already parentheses that make it clear: if (more than half the MPI size are requesting write) or (any workers are requesting a write and all jobs have received a poison pill).

**Comment by krischer** [comment] 2015-11-09 23:00
> There are already parentheses that make it clear: if (more than half the MPI size are requesting write) or (any workers are requesting a write and all jobs have received a poison pill).

Exactly. The 0.5 is arbitrary but seems to work quite well. The problem is that before any processor can write to the file the metadata must be synchronized across all ranks. This would be terribly inefficient to do after every processed stream thus each rank buffers data up to a certain memory limit and then requests a write from the master rank. Once more then 50 % of the worker request a write the master will force all ranks to start the synchronization.

@wjlei1990 Can you upload the files + scripts you use so I can test them locally?

Are you on Python 2 or Python 3? I sometimes have issue to get the parallel I/O to work on Python 3 for some reason.

**Comment by krischer** [comment] 2015-11-18 08:26
@wjlei1990 Does 484f41f211fa5d6c753e793c5d215d1cb30124c7 also fix this issue here? If not - can you upload files and scripts somewhere and I'll have a look.

**Comment by wjlei1990** [comment] 2015-11-19 21:56
Hi Lion, 

The commit you mentioned above still doesn't fix the problem.

I will upload files somewhere so you can have a look.

You have access to clover, right? 

My data file is about 100MB for each. And I will give you 10, so the total size would be 1GB.

**Comment by krischer** [comment] 2015-11-19 22:00
Yes I have access to clover so putting the files there would be great. I'll have a look tomorrow.

**Comment by wjlei1990** [comment] 2015-11-19 22:29
Yes. I will try to upload the files tonight. 

The disk on clover is full now and we are trying to delete some files to makeup some space :imp:

**Comment by krischer** [comment] 2015-11-20 11:44
Did you upload the files somewhere? If its only a GB you can also just put it into dropbox or google or any other service. I would also need your scripts with the processing.

**Comment by wjlei1990** [comment] 2015-11-23 17:21
Hi Lion,

I have upload files on sdf@seismo.princeton.edu. It is located at: /home/sdf/preproc_lion_test.

There are two example bash files you can run:
1) run_one_file_test.bash: process just one file. So this test should pass with no error.

2) run_multi_file_test.bash: process 10 files at one time. So this test should fail at a certain point. One thing I noticed that if you use more cores, you will fail more quickly. For example, if you use 4 cores, it can fail after 7 or 8 files. If you use 16 cores, it could fail after 2-3 files.

Let me you if you have problem with getting those files.

**Comment by krischer** [comment] 2015-11-23 20:30
Thanks. I'll try this tomorrow!

**Comment by krischer** [comment] 2015-11-30 23:34
This was nasty but I think I fixed it in 05f21b4d006feeced0904f8a3d87c951f981704a. Can you test on your machine?

The problem was that some MPI messages that were sent while processing one file did not get received so they got received while processing the next file which of course screws everything up. It only happened in specific situations. It now collects any left-over messages before shutting down the nodes so it is ready to process the next file without any previous state.

Man...our brains are really not made for dealing the parallel programs...

**Comment by wjlei1990** [comment] 2015-12-01 18:58
AHA! Great job, Lion.

I have tested it on my machine, using 8, 16 and 32 processors. It works like a charm :)

I initially thought it was some MPI library issue.

**Closed** 2015-12-01 18:58 UTC

**Comment by QuLogic** [comment] 2015-12-01 23:17
> Man...our brains are really not made for dealing the parallel programs...

Yea, that's why there's so many RabbitMQ, ZeroMQ, etc....
